[package]
name = "pan"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4"
rand = "0.8"
console_engine = "2.0"
serde = { version = "1.0", features = ["derive"] }
rmp-serde = "0.15"